
### Variables
@port = 3000
@id = 661d73ee17d68530513b1e2f

### Get todos

GET http://localhost:{{port}}/api/todos

### Create a todo

POST http://localhost:{{port}}/api/todos
Content-Type: application/json

{
  "item": "Finish the Assignment"
}

### Toggle completed status of a todo

PUT http://localhost:{{port}}/api/todos/{{id}}


